### ISSUE TITLE
SEL no longer monitored for all events since 3.9

### ISSUE THREAD

**Issue by veitw** [thomas-krenn/check_ipmi_sensor_v3#1]
Hi,

please revert check_ipmi_sensor's SEL functionality back to the behaviour that was used up to version 3.8; monitoring every single SEL event instead of only memory (3.9, 3.10) and processor (3.10) events.

I consider the new behaviour harmful as a lot of problems will never be detected and flaky problems would not trigger alarms as everything appears just fine during monitoring checks, although the SEL contains logged events.
Also other events required for the current behaviour are not monitored at the moment, for example SEL full events. Thus limiting the monitoring of SEL to memory and processor would eventually even prevent detecting problems with those as no new events can be logged once the SEL is full.

Please revert to the former behaviour to monitoring all SEL events and add a new option to check_ipmi_sensor, e.g. "--sel-sensor-types", so sysadmins that only want to monitor SEL for memory and processor events can use "--sel-sensor-types Memory,Processor" to limit monitoring.

Thank you,
// Veit

**Comment by gschoenberger** [comment]
Thanks for the issue!
Now fixed with commit 588fdafecc6484f7c7046b4bb73e10b075af7310
An new option '-ST' or '--sel-sensor-types' can be used to specify custom SEL sensor types.

Per default now using 'all' again,
cheers Georg
