### ISSUE TITLE
Help: Hosts with different password?

### ISSUE THREAD

**Issue by hoxis** [thomas-krenn/check_ipmi_sensor_v3#15]
hosts with different password, how to configure ?

**Comment by tk-wfischer** [comment]
I'd sugguest to use individueal FreeIPMI config files (-f option):
https://github.com/thomas-krenn/check_ipmi_sensor_v3/blob/master/check_ipmi_sensor#L70

**Comment by gschoenberger** [comment]
Closing this, as solved with multiple config files
