### ISSUE TITLE
Optional additional FRU information in output

### ISSUE THREAD

**Issue by MarcusCaepio** [thomas-krenn/check_ipmi_sensor_v3#41]
Good morning y'all,
Beside the serial number, we are also interested in the Asset Tag and Board Information in the output.
I am currently working on "--assettag" and "--board" options to display them. My idea is, that "--fru" is mandatory for both new options. This way, the script just uses the already existent "@fruoutput" and the code just has to be expanded a little bit. 

I would create a PR, when it's finished.
Cheers and have a nice weekend,
Marcus

**Comment by gschoenberger** [comment]
Yes! Please create a PR and I will review/merge it,

TXH - Georg

**Comment by MarcusCaepio** [comment]
Hi Georg,
PR is done. If you merge it, I will re-fork the [Icinga2](https://github.com/Icinga/icinga2) Repo, adjust the ITL command and create a PR for it to have the current version also running with the next release.

Cheers,
Marcus
