### ISSUE TITLE
Dell idrac9 disk error not shown in the output

### ISSUE THREAD

**Issue by selcukKaraca** [thomas-krenn/check_ipmi_sensor_v3#47]
for dell servers idrac9 we had a SSD disk failure. but this does not shown in the plugin output. I have enabled verbose mode (-vvv) we have more than 10 disks (physical and virtual) but plugin output only shows 2 "Drive Slot". No other disk info in the verbose output. why does plugin output not show disk failure?

I see disk drive failures in IPMI output in other server types. this can be related with dell idrac..

as a workaround, if we enable SEL, then we could see the disk related event. bu we normally skip sel logs as this is too noisy for us. 

thanks four your help..

**Comment by gschoenberger** [comment]
As far as I can assume this is nothing plugin related but quite DELL specific.
My proposal is to contact your DELL support why SSD failures are not promoted via IPMI.
As the plugin only checks but doesn't filter the output you first have to ensure that the corresponding failures are shown by IPMI.
